server:
  port: 9002

spring:
  application:
    name: cluster
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.227.128:1111
        #server-addr: localhost:8848 #配置Nacos地址


management:
  endpoints:
    web:
      exposure:
        include: '*'